### PR TITLE
Figure with temperature and flux evolutions

### PR DESCRIPTION
**Pull request by KulaginVladimir**
@RemDelaporteMathurin 

There are some minor changes in the model and a new figure with temporal dependencies of temperature and D flux during exposure (D in Eurofer case).

image

### CODE REVIEW

**Review by RemDelaporteMathurin — APPROVED** [review]
I would add some documentation in the `T(t)` function saying that this is taken from the TESSIM files. Looks like the changes in the model don't affect the results at all?

**Comment by KulaginVladimir** [comment]
> I would add some documentation in the T(t) function saying that this is taken from the TESSIM files. 

In the code?

> Looks like the changes in the model don't affect the results at all?

Yes, these changes affect the parameters in the FESTIM model, but not their product (defines the rate of transitions). The only thing that I've changed is the factor of 6, which is the ratio between concentration of interstitial sites in a bcc metal and concentration of host atoms. 

Meanwhile, there is a point to discuss. The authors defined the pre-factor of diffusion-limited trapping rate (in FESTIM notation) as $D_0/(\lambda^2 6 n_{EFe})=D_0/(\lambda^2 n_{IS})$, but for the surface model the rate pre-factor of bulk-to-surface transition as $D_0/(\lambda^2 n_{EFe})$, what do not agree with the definition in other cases.

**Comment by KulaginVladimir** [comment]
pinging @RemDelaporteMathurin to deal with issue above

**Comment by RemDelaporteMathurin** [comment]
> In the code?

Yes, as docstrings of the large `T` function.

**Pull request merged**
