### PR TITLE
upd diagram

### PR DESCRIPTION
**Pull request by KulaginVladimir**
This PR updates the potential energy diagram, but we need to hear @ehodille opinion.

### CODE REVIEW

**Comment by ehodille** [comment]
How can I visualise the potential energy diagrams ?

**Comment by KulaginVladimir** [comment]
@ehodille, here you are. Should we have 2 diagrams based on your sketch?

image

[potential_diagram_new.pdf](https://github.com/user-attachments/files/17680783/potential_diagram_new.pdf)

**Comment by ehodille** [comment]
Ha yes, that is perfect.
I think only this diagram is good.
The other diagram is not necessary, especially if you mention in the paper the relationship between the kinetic energy barrier and the heat of solution

**Comment by KulaginVladimir** [comment]
@ehodille, alright

**Comment by RemDelaporteMathurin** [comment]
> How can I visualise the potential energy diagrams ?

Simply go to the "Files changed" tab:

image

**Comment by KulaginVladimir** [comment]
@ehodille
In the paper, we also state that sputtering and desorption of atoms are possible. What's you opinion, should we add $2E_H$ energy level to this diagram?

**Comment by KulaginVladimir** [comment]
@ehodille, what do you think of this diagram? 

image

**Pull request merged**
