### PR TITLE
Fix figures using Latex in binder

### LINKED ISSUE #25: Fix figures using Latex in binder
Related to this issue https://github.com/jupyterhub/mybinder.org-user-guide/issues/211 we need to add a `apt.txt` file to properly install Latex in binder.

Similar to what is done here: https://github.com/binder-examples/latex

### PR DESCRIPTION
**Pull request by KulaginVladimir**
Based on [this example](https://github.com/binder-examples/latex), fixes #25

### CODE REVIEW

**Comment by KulaginVladimir** [comment]
@RemDelaporteMathurin, I suppose I should merge this to check the figures in Binder

**Comment by RemDelaporteMathurin** [comment]
> @RemDelaporteMathurin, I suppose I should merge this to check the figures in Binder

Either that or make a new binder based on this branch

**Comment by RemDelaporteMathurin** [comment]
Do you need to add the packages you use too? Like siunitx etc

**Comment by KulaginVladimir** [comment]
> Either that or make a new binder based on this branch

I thought it runs from the main branch only (apparently, it's not)

> Do you need to add the packages you use too? Like siunitx etc

Maybe, I'll check

**Review by RemDelaporteMathurin — APPROVED** [review]

**Pull request merged**
